In [4]:
import pandas as pd
import numpy as np
import os
from sklearn.datasets import fetch_california_housing
from sklearn.preprocessing import StandardScaler

### データの読み込みと前処理（標準化）

In [3]:
# カルフォルニア住宅価格のデータセットをロード
datapath = "./california_housing.csv"
if os.path.exists(datapath):
    df = pd.read_csv(datapath)
    df = df.drop(columns="Unnamed: 0")
else:
    calif = fetch_california_housing()
    df = pd.DataFrame(calif.data, columns = calif.feature_names).assign(Price=np.array(calif.target))

df.describe()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Price
count,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,3.870671,28.639486,5.429000,1.096675,1425.476744,3.070655,35.631861,-119.569704,2.068558
std,1.899822,12.585558,2.474173,0.473911,1132.462122,10.386050,2.135952,2.003532,1.153956
min,0.499900,1.000000,0.846154,0.333333,3.000000,0.692308,32.540000,-124.350000,0.149990
25%,2.563400,18.000000,4.440716,1.006079,787.000000,2.429741,33.930000,-121.800000,1.196000
50%,3.534800,29.000000,5.229129,1.048780,1166.000000,2.818116,34.260000,-118.490000,1.797000
75%,4.743250,37.000000,6.052381,1.099526,1725.000000,3.282261,37.710000,-118.010000,2.647250
max,15.000100,52.000000,141.909091,34.066667,35682.000000,1243.333333,41.950000,-114.310000,5.000010